# Generated by Django 2.0.6 on 2018-06-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180606_0915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userask',
            old_name='course',
            new_name='course_name',
        ),
        migrations.AddField(
            model_name='userask',
            name='is_delete',
            field=models.BooleanField(choices=[(0, '未处理'), (1, '已处理')], default=0, verbose_name='是否已处理'),
        ),
    ]
