# Generated by Django 2.0.6 on 2018-06-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180608_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermessage',
            old_name='user',
            new_name='user_id',
        ),
    ]
