# Generated by Django 2.0.5 on 2018-05-29 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='course_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Organizationinfo', verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='courseinfo',
            name='name',
            field=models.CharField(max_length=100, verbose_name='课程名称'),
        ),
    ]
