# Generated by Django 2.0.6 on 2018-06-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseinfo_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='notice',
            field=models.CharField(default='暂无公告', max_length=300, verbose_name='课程公告'),
        ),
    ]
