# Generated by Django 2.0.6 on 2018-06-08 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180608_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '小节/视频', 'verbose_name_plural': '小节/视频'},
        ),
        migrations.AlterField(
            model_name='courseresource',
            name='download',
            field=models.FileField(upload_to='courses/resource/%Y/%m', verbose_name='资料下载'),
        ),
        migrations.AlterField(
            model_name='lession',
            name='name',
            field=models.CharField(max_length=100, verbose_name='章名'),
        ),
        migrations.AlterField(
            model_name='video',
            name='lession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Lession', verbose_name='章'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, verbose_name='小节/视频名称'),
        ),
    ]
