# Generated by Django 2.0.6 on 2018-07-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180702_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfo',
            name='detail',
            field=models.TextField(verbose_name='课程详情'),
        ),
    ]
