# Generated by Django 2.0.6 on 2018-07-14 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180702_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.FileField(upload_to='courses/video/%Y/%m', verbose_name='播放地址'),
        ),
    ]
