# Generated by Django 2.0.6 on 2018-06-10 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180608_1806'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Courseinfo', verbose_name='课程'),
        ),
    ]
