# Generated by Django 2.0.6 on 2018-06-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_banner_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='banner_url',
        ),
    ]
