# Generated by Django 2.0.5 on 2018-06-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationinfo',
            name='image',
            field=models.ImageField(upload_to='orgs/%Y/%m', verbose_name='机构logo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='default1.png', upload_to='teachers/%Y/%m', verbose_name='教师头像'),
        ),
    ]
