# Generated by Django 2.0.6 on 2018-06-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinfo',
            name='course_nums',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default='default1.png', upload_to='teachers/%Y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Organizationinfo', verbose_name='就职单位'),
        ),
    ]
