# Generated by Django 2.0.6 on 2018-06-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20180611_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinfo',
            name='course_nums',
            field=models.IntegerField(default=0, verbose_name='课程数'),
        ),
    ]
