# Generated by Django 2.0.6 on 2018-06-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organizationinfo_course_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinfo',
            name='is_authentication',
            field=models.BooleanField(choices=[(0, '未认证'), (1, '已认证')], default=0, verbose_name='是否已认证'),
        ),
        migrations.AddField(
            model_name='organizationinfo',
            name='is_gold',
            field=models.BooleanField(choices=[(0, '非金牌机构'), (1, '金牌机构')], default=0, verbose_name='是否为金牌机构'),
        ),
    ]
