# Generated by Django 2.0.6 on 2018-06-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20180607_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_authentication',
            field=models.BooleanField(choices=[(0, '未认证'), (1, '已认证')], default=0, verbose_name='是否已认证'),
        ),
    ]
