# Generated by Django 2.0.6 on 2018-06-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_teacher_is_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationinfo',
            name='course_nums',
        ),
    ]
