# Generated by Django 2.0.6 on 2018-06-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organizationinfo_course_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_gold',
            field=models.BooleanField(choices=[(0, '非金牌教师'), (1, '金牌教师')], default=0, verbose_name='是否为金牌教师'),
        ),
    ]
